apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_BASE_URL
              value: "change-here"
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui-volume
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: open-webui-volume
          persistentVolumeClaim:
            claimName: open-webui-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: open-webui
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: open-webui-route
spec:
  to:
    kind: Service
    name: open-webui-service
  port:
    targetPort: 8080
  tls:
    termination: edge

